2023-02-14 02:44:10,954 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2023-02-14 02:44:10,963 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'activate_service_account']
2023-02-14 02:44:10,966 DEBUG    root            Running [gcloud.auth.activate-service-account] with arguments: [--key-file: ".~/.gc/second-chariot-375510-cf05a71f2b3e.json"]
2023-02-14 02:44:10,966 DEBUG    root            (gcloud.auth.activate-service-account) Unable to read file [.~/.gc/second-chariot-375510-cf05a71f2b3e.json]: [Errno 2] No such file or directory: '.~/.gc/second-chariot-375510-cf05a71f2b3e.json'
Traceback (most recent call last):
  File "/snap/google-cloud-cli/105/lib/googlecloudsdk/core/util/files.py", line 1299, in _FileOpener
    return io.open(path, mode, encoding=encoding, newline=newline)
FileNotFoundError: [Errno 2] No such file or directory: '.~/.gc/second-chariot-375510-cf05a71f2b3e.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/google-cloud-cli/105/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/snap/google-cloud-cli/105/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/snap/google-cloud-cli/105/lib/surface/auth/activate_service_account.py", line 100, in Run
    file_content, is_json = _IsJsonFile(args.key_file)
  File "/snap/google-cloud-cli/105/lib/surface/auth/activate_service_account.py", line 147, in _IsJsonFile
    content = console_io.ReadFromFileOrStdin(filename, binary=True)
  File "/snap/google-cloud-cli/105/lib/googlecloudsdk/core/console/console_io.py", line 140, in ReadFromFileOrStdin
    return files.ReadBinaryFileContents(path)
  File "/snap/google-cloud-cli/105/lib/googlecloudsdk/core/util/files.py", line 1097, in ReadBinaryFileContents
    with BinaryFileReader(path) as f:
  File "/snap/google-cloud-cli/105/lib/googlecloudsdk/core/util/files.py", line 1212, in BinaryFileReader
    return _FileOpener(encoding_util.Encode(path, encoding='utf-8'), 'rb', 'read')
  File "/snap/google-cloud-cli/105/lib/googlecloudsdk/core/util/files.py", line 1306, in _FileOpener
    raise exc_type('Unable to {0} file [{1}]: {2}'.format(verb, path, e))
googlecloudsdk.core.util.files.MissingFileError: Unable to read file [.~/.gc/second-chariot-375510-cf05a71f2b3e.json]: [Errno 2] No such file or directory: '.~/.gc/second-chariot-375510-cf05a71f2b3e.json'
2023-02-14 02:44:10,974 ERROR    root            (gcloud.auth.activate-service-account) Unable to read file [.~/.gc/second-chariot-375510-cf05a71f2b3e.json]: [Errno 2] No such file or directory: '.~/.gc/second-chariot-375510-cf05a71f2b3e.json'
